meta_product_name: "AltrooistApp"
meta_title: "Altrooist - Kindness in action"
meta_description: "100+ volunteer opportunities across Quebec, curated search results just for you."
meta_image: "cover.png" # should exist in `app/assets/images/`
